version: "3.8"

services:
  app:
    build: .
    container_name: rewrapped-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rewrapped
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:17
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_DB: rewrapped
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
