service: rewrapped-api

frameworkVersion: "3"

provider:
  name: aws
  region: eu-central-1
  stage: ${opt:stage, 'prod'}
  environment:
    MAIN_CLASS: com.spotify.rewrapped.RewrappedApplication
    PORT: 3000
    DATASOURCE_URL: ${ssm:/rewrapped/prod/db-url}
    DATASOURCE_USERNAME: ${ssm:/rewrapped/prod/db-username}
    DATASOURCE_PASSWORD: ${ssm:/rewrapped/prod/db-password,true}
    UI_URL: https://spotify-rewrapped-ui.onrender.com

package:
  artifact: target/rewrapped-0.0.1.jar

functions:
  handler:
    memorySize: 1024
    timeout: 30
    runtime: java17
    snapStart: true
    handler: com.spotify.rewrapped.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
          private: true

apiGateway:
  apiKeys:
    - name: rewrapped-api-key
  usagePlan:
    quota:
      limit: 1000
      period: MONTH
    throttle:
      rateLimit: 100
      burstLimit: 10

resources:
  Resources:
    lambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: rewrapped-api-lambda-execution-role-${sls:stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: rewrapped-api-lambda-execution-policy-${sls:stage}
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogStream"
                    - "logs:TagResource"
                    - "logs:CreateLogGroup"
                    - "logs:PutLogEvents"
                  Resource:
                    - "arn:aws:logs:*:*:log-group:/aws/lambda/*"
                - Effect: Allow
                  Action:
                    - "ssm:GetParameter"
                    - "ssm:GetParameters"
                    - "ssm:GetParametersByPath"
                  Resource:
                    - "arn:aws:ssm:*"
